// Generated by Wrangler on Wed Sep 11 2024 23:35:42 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	ROOM: DurableObjectNamespace;
	LIMITER: DurableObjectNamespace;
}
